// <auto-generated />
namespace SleepMakeSense.Migrations.SleepbetaDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adddistance_and_heartrate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adddistance_and_heartrate));
        
        string IMigrationMetadata.Id
        {
            get { return "201712180730048_add-distance_and_heartrate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
