// <auto-generated />
namespace SleepMakeSense.Migrations.SleepbetaDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changedatatype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedatatype));
        
        string IMigrationMetadata.Id
        {
            get { return "201712190143510_change-datatype"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
