// <auto-generated />
namespace SleepMakeSense.Migrations.SleepbetaDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class modify_Logid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modify_Logid));
        
        string IMigrationMetadata.Id
        {
            get { return "201801150620538_modify_Logid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
