// <auto-generated />
namespace SleepMakeSense.Migrations.SleepbetaDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedspeeds : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedspeeds));
        
        string IMigrationMetadata.Id
        {
            get { return "201801090559194_added-speeds"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
